service: serverless-boilerplate

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-prune-plugin
  - serverless-offline # serverless-offline needs to be last in the list.

frameworkVersion: '>=1.44.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs12.x # Latest version supported.
  stage: local # Default stage.
  region: eu-west-1 # Default region.
  timeout: 10 # Default Lambda timeout.
  memorySize: 512 # Default Lambda Memory Size.
  profile: YOUR_PROFILE # Default profile to use. Don't forget to amend this value.
  deploymentBucket:
    name: serverless-boilerplate-eu-west-1-deploy # Your chosen S3 bucket for deployment.
  stackTags:
    project: ${self:service}
    env: ${self:custom.stage}
  logs:
    restApi: true

  tracing:
    apiGateway: true
    lambda: true

  environment: ${file(./configs/${self:custom.stage}.yml)}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'

package:
  individually: true
  exclude:
    - .git/**
    - .vscode/**
    - .test/**

custom:
  # Our stage/region are based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

  serverless-iam-roles-per-function:
    defaultInherit: true

  apigwBinary:
    types:
      - 'multipart/form-data'

  prune:
    automatic: true
    number: 5 # Number of versions of your lambda to keep.

  stackname: ${self:service}-${self:custom.stage}

  bucket: targoo-serverless-boilerplate

  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'

  dynamodb:
    stages:
      - local
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      seed: true
      convertEmptyValues: true
      migrate: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

functions: ${file(resources/lambdas/loader.js)}

resources:
  - ${file(resources/api/api.yml)}
  - ${file(resources/dynamodbs/main.yml)}
