Resources:
  MainTable:
    Type: AWS::DynamoDB::Table
    Description: 'Main'
    Properties:
      TableName: ${self:custom.stackname}-main
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'relation'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
        - AttributeName: 'relation'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  TableArn:
    Value:
      Fn::GetAtt:
        - MainTable
        - Arn
    Export:
      Name: ${self:service}-table-arn
